name: 'Setup Node with Cache'
description: 'Setup Node.js with caching for node_modules and install dependencies'
inputs:
  node-version:
    description: 'Node.js version'
    required: false
    default: '22'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: yarn

    - name: Install dependencies
      run: yarn install --frozen-lockfile
      shell: bash