name: 'Setup Repo'
description: 'Setup everything needed to build, run tests, publish, etc'
inputs:
  node-version:
    description: 'Node.js version'
    required: false
    default: '22'
  use-android-cache:
    description: "Cache JDK, Gradle, etc for android build"
    required: false
    type: boolean
    default: true

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: yarn

    - name: Cache dependencies
      id: yarn-cache
      uses: actions/cache@v3
      with:
        path: |
          **/node_modules
          !examples/embedded-accounts-quickstart
          .yarn/install-state.gz
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}-${{ hashFiles('**/package.json', '!node_modules/**') }}
        restore-keys: |
          ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile
      shell: bash
    
    # Foundry setup
    - name: Set up foundry
      uses: foundry-rs/foundry-toolchain@v1
    
    # Android setup
    - name: Check turborepo cache for Android
      if: inputs.use-android-cache == true
      shell: bash
      run: |
        TURBO_CACHE_STATUS=$(node -p "($(yarn turbo run build:android --dry=json | sed '1,2d;$d')).tasks.find(t => t.task === 'build:android').cache.status")

        if [[ $TURBO_CACHE_STATUS == "HIT" ]]; then
          echo "turbo_cache_hit=1" >> $GITHUB_ENV
        fi

    - name: Install JDK
      if: env.turbo_cache_hit != 1
      uses: actions/setup-java@v3
      with:
        distribution: "zulu"
        java-version: "17"

    - name: Finalize Android SDK
      if: env.turbo_cache_hit != 1
      shell: bash
      run: |
        /bin/bash -c "yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses > /dev/null"

    - name: Cache Gradle
      if: env.turbo_cache_hit != 1
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/wrapper
          ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('account-kit/rn-signer/examples/rn-bare/android/gradle/wrapper/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-