
# Base URL or website root directory to check relative URLs.
base_url = "https://www.alchemy.com"

exclude = [
    ".*\\.mdx$",             # Links to MDX files - these should only be for snippets, not HTML pages
    ".*\\.png$",             # All PNG files 
    ".*\\.pdf$",             # All PDF files 
    ".*g\\.alchemy\\.com.*", # Any path containing g.alchemy.com - RPC endpoints require API keys
]

exclude_path = [
    "docs/pages/reference/.*", # Exclude the entire reference directory from link checking
]

# Comma-separated list of accepted status codes for valid links.
accept = [200, 403]

# Maximum number of allowed retries before a link is declared dead.
max_retries = 5

# Minimum wait time in seconds between retries of failed requests.
retry_wait_time = 5

# User agent to send with each request.
user_agent = "lychee/link-checker"
