name: 'Setup Docs'
description: 'Sets up everything needed to generate docs with Fern CLI'

inputs:
  docs-github-token:
    description: 'GitHub token for accessing the docs repository'
    required: true

runs:
  using: "composite"
  steps:
    - name: Extract code snippets
      shell: bash
      run: node docs/scripts/extract-include-statements.js

    - name: Ensure docs-site submodule is up-to-date
      shell: bash
      run: git submodule update --init --recursive

    - name: Insert Account Kit docs.yml into docs-site/fern/docs.yml
      shell: bash
      run: |
        docs/scripts/insert-docs.sh aa-sdk
