import { DefaultTheme } from "vitepress/types/default-theme";

export const aaSignersSidebar: DefaultTheme.SidebarItem = {
  text: "aa-signers",
  collapsed: true,
  base: "/packages/aa-signers",
  items: [
    {
      text: "Getting started",
      link: "/",
    },
    {
      text: "Magic Signer",
      collapsed: true,
      base: "/packages/aa-signers/magic",
      items: [
        { text: "Introduction", link: "/introduction" },
        { text: "constructor", link: "/constructor" },
        { text: "authenticate", link: "/authenticate" },
        { text: "getAddress", link: "/getAddress" },
        { text: "signMessage", link: "/signMessage" },
        { text: "signTypedData", link: "/signTypedData" },
        { text: "getAuthDetails", link: "/getAuthDetails" },
      ],
    },
    {
      text: "Web3Auth Signer",
      collapsed: true,
      base: "/packages/aa-signers/web3auth",
      items: [
        { text: "Introduction", link: "/introduction" },
        { text: "constructor", link: "/constructor" },
        { text: "authenticate", link: "/authenticate" },
        { text: "getAddress", link: "/getAddress" },
        { text: "signMessage", link: "/signMessage" },
        { text: "signTypedData", link: "/signTypedData" },
        { text: "getAuthDetails", link: "/getAuthDetails" },
      ],
    },
    {
      text: "Turnkey Signer",
      collapsed: true,
      base: "/packages/aa-signers/turnkey",
      items: [
        { text: "Introduction", link: "/introduction" },
        { text: "constructor", link: "/constructor" },
        { text: "authenticate", link: "/authenticate" },
        { text: "getAddress", link: "/getAddress" },
        { text: "signMessage", link: "/signMessage" },
        { text: "signTypedData", link: "/signTypedData" },
        { text: "getAuthDetails", link: "/getAuthDetails" },
      ],
    },
    {
      text: "Fireblocks Signer",
      collapsed: true,
      base: "/packages/aa-signers/fireblocks",
      items: [
        { text: "Introduction", link: "/introduction" },
        { text: "constructor", link: "/constructor" },
        { text: "authenticate", link: "/authenticate" },
        { text: "getAddress", link: "/getAddress" },
        { text: "signMessage", link: "/signMessage" },
        { text: "signTypedData", link: "/signTypedData" },
        { text: "getAuthDetails", link: "/getAuthDetails" },
      ],
    },
    {
      text: "Capsule Signer",
      collapsed: true,
      base: "/packages/aa-signers/capsule",
      items: [
        { text: "Introduction", link: "/introduction" },
        { text: "constructor", link: "/constructor" },
        { text: "authenticate", link: "/authenticate" },
        { text: "getAddress", link: "/getAddress" },
        { text: "signMessage", link: "/signMessage" },
        { text: "signTypedData", link: "/signTypedData" },
        { text: "getAuthDetails", link: "/getAuthDetails" },
      ],
    },
    {
      text: "Particle Signer",
      collapsed: true,
      base: "/packages/aa-signers/particle",
      items: [
        { text: "Introduction", link: "/introduction" },
        { text: "constructor", link: "/constructor" },
        { text: "authenticate", link: "/authenticate" },
        { text: "getAddress", link: "/getAddress" },
        { text: "signMessage", link: "/signMessage" },
        { text: "signTypedData", link: "/signTypedData" },
        { text: "getAuthDetails", link: "/getAuthDetails" },
      ],
    },
    {
      text: "Portal Signer",
      collapsed: true,
      base: "/packages/aa-signers/portal",
      items: [
        { text: "Introduction", link: "/introduction" },
        { text: "constructor", link: "/constructor" },
        { text: "authenticate", link: "/authenticate" },
        { text: "getAddress", link: "/getAddress" },
        { text: "signMessage", link: "/signMessage" },
        { text: "signTypedData", link: "/signTypedData" },
        { text: "getAuthDetails", link: "/getAuthDetails" },
      ],
    },
    {
      text: "Arcana Auth Signer",
      collapsed: true,
      base: "/packages/aa-signers/arcana-auth",
      items: [
        { text: "Introduction", link: "/introduction" },
        { text: "constructor", link: "/constructor" },
        { text: "authenticate", link: "/authenticate" },
        { text: "getAddress", link: "/getAddress" },
        { text: "signMessage", link: "/signMessage" },
        { text: "signTypedData", link: "/signTypedData" },
        { text: "getAuthDetails", link: "/getAuthDetails" },
      ],
    },
    {
      text: "Lit Signer",
      collapsed: true,
      base: "/packages/aa-signers/lit-protocol",
      items: [
        { text: "Introduction", link: "/introduction" },
        { text: "constructor", link: "/constructor" },
        { text: "authenticate", link: "/authenticate" },
        { text: "getAddress", link: "/getAddress" },
        { text: "signMessage", link: "/signMessage" },
        { text: "signTypedData", link: "/signTypedData" },
        { text: "getAuthDetails", link: "/getAuthDetails" },
      ],
    },
    {
      text: "Passport Signer",
      collapsed: true,
      base: "/packages/aa-signers/passport",
      items: [
        { text: "Introduction", link: "/introduction" },
        { text: "constructor", link: "/constructor" },
        { text: "authenticate", link: "/authenticate" },
        { text: "getAddress", link: "/getAddress" },
        { text: "signMessage", link: "/signMessage" },
        { text: "signTypedData", link: "/signTypedData" },
        { text: "getAuthDetails", link: "/getAuthDetails" },
      ],
    },
    {
      text: "Fordefi Signer",
      collapsed: true,
      base: "/packages/aa-signers/fordefi",
      items: [
        { text: "Introduction", link: "/introduction" },
        { text: "constructor", link: "/constructor" },
        { text: "authenticate", link: "/authenticate" },
        { text: "getAddress", link: "/getAddress" },
        { text: "signMessage", link: "/signMessage" },
        { text: "signTypedData", link: "/signTypedData" },
        { text: "getAuthDetails", link: "/getAuthDetails" },
      ],
    },
    { text: "Contributing", link: "/contributing" },
  ],
};
