// This file is autogenerated, see scripts/prebuild.ts
import { SidebarItem } from "vocs";

export const accountKitCoreReferenceSidebar: SidebarItem[] = [
  {
    text: "@account-kit/core",
    items: [
      {
        text: "Overview",
        link: "/reference/account-kit/core",
      },
    ],
  },
  {
    text: "Functions",
    items: [
      {
        text: "cookieStorage",
        link: "/reference/account-kit/core/functions/cookieStorage",
      },
      {
        text: "cookieToInitialState",
        link: "/reference/account-kit/core/functions/cookieToInitialState",
      },
      {
        text: "createAccount",
        link: "/reference/account-kit/core/functions/createAccount",
      },
      {
        text: "createConfig",
        link: "/reference/account-kit/core/functions/createConfig",
      },
      {
        text: "defaultAccountState",
        link: "/reference/account-kit/core/functions/defaultAccountState",
      },
      {
        text: "disconnect",
        link: "/reference/account-kit/core/functions/disconnect",
      },
      {
        text: "getAccount",
        link: "/reference/account-kit/core/functions/getAccount",
      },
      {
        text: "getBundlerClient",
        link: "/reference/account-kit/core/functions/getBundlerClient",
      },
      {
        text: "getChain",
        link: "/reference/account-kit/core/functions/getChain",
      },
      {
        text: "getConnection",
        link: "/reference/account-kit/core/functions/getConnection",
      },
      {
        text: "getSigner",
        link: "/reference/account-kit/core/functions/getSigner",
      },
      {
        text: "getSignerStatus",
        link: "/reference/account-kit/core/functions/getSignerStatus",
      },
      {
        text: "getSmartAccountClient",
        link: "/reference/account-kit/core/functions/getSmartAccountClient",
      },
      {
        text: "getUser",
        link: "/reference/account-kit/core/functions/getUser",
      },
      {
        text: "hydrate",
        link: "/reference/account-kit/core/functions/hydrate",
      },
      {
        text: "parseCookie",
        link: "/reference/account-kit/core/functions/parseCookie",
      },
      {
        text: "reconnect",
        link: "/reference/account-kit/core/functions/reconnect",
      },
      {
        text: "setChain",
        link: "/reference/account-kit/core/functions/setChain",
      },
      {
        text: "watchAccount",
        link: "/reference/account-kit/core/functions/watchAccount",
      },
      {
        text: "watchBundlerClient",
        link: "/reference/account-kit/core/functions/watchBundlerClient",
      },
      {
        text: "watchChain",
        link: "/reference/account-kit/core/functions/watchChain",
      },
      {
        text: "watchConnection",
        link: "/reference/account-kit/core/functions/watchConnection",
      },
      {
        text: "watchSigner",
        link: "/reference/account-kit/core/functions/watchSigner",
      },
      {
        text: "watchSignerStatus",
        link: "/reference/account-kit/core/functions/watchSignerStatus",
      },
      {
        text: "watchSmartAccountClient",
        link: "/reference/account-kit/core/functions/watchSmartAccountClient",
      },
      {
        text: "watchUser",
        link: "/reference/account-kit/core/functions/watchUser",
      },
    ],
  },
  {
    text: "Classes",
    items: [
      {
        text: "ClientOnlyPropertyError",
        items: [
          {
            text: "constructor",
            link: "/reference/account-kit/core/classes/ClientOnlyPropertyError/constructor",
          },
        ],
      },
    ],
  },
  {
    text: "Resources",
    items: [
      {
        text: "React Native",
        items: [
          {
            text: "Overview",
            link: "/react-native/overview",
          },
          {
            text: "Getting Started",
            items: [
              {
                text: "Getting started on Expo",
                link: "/react-native/getting-started/getting-started-expo",
              },
              {
                text: "Getting started on Bare React Native",
                link: "/react-native/getting-started/getting-started-rn-bare",
              },
            ],
          },
          {
            text: "Using the Signer",
            items: [
              {
                text: "Overview",
                link: "/react-native/signer/overview",
              },
              {
                text: "Setup",
                link: "/react-native/signer/setup-guide",
              },
              {
                text: "Authenticating Users",
                link: "/react-native/signer/authenticating-users",
              },
              {
                text: "Bare React Native Installation",
                link: "/react-native/signer/bare-installation",
              },
            ],
          },
        ],
        collapsed: true,
      },
      {
        text: "Third Party",
        items: [
          {
            text: "Bundlers",
            link: "/third-party/bundlers",
          },
          {
            text: "Chains",
            link: "/third-party/chains",
          },
          {
            text: "Paymasters",
            link: "/third-party/paymasters",
          },
          {
            text: "Signers",
            link: "/third-party/signers",
          },
          {
            text: "Smart Contracts",
            link: "/third-party/smart-contracts",
          },
        ],
        collapsed: true,
      },
      {
        text: "Terms",
        link: "/resources/terms",
      },
      {
        text: "Types",
        link: "/resources/types",
      },
      {
        text: "FAQs",
        link: "/resources/faqs",
      },
      {
        text: "Contact us",
        link: "/resources/contact-us",
      },
    ],
  },
];
