// This file is autogenerated, see scripts/prebuild.ts
import { SidebarItem } from "vocs";

export const accountKitCoreReferenceSidebar: SidebarItem[] = [
  {
    text: "@account-kit/core",
    items: [
      {
        text: "Overview",
        link: "/reference/account-kit/core",
      },
    ],
  },
  {
    text: "Functions",
    items: [
      {
        text: "cookieStorage",
        link: "/reference/account-kit/core/functions/cookieStorage",
      },
      {
        text: "cookieToInitialState",
        link: "/reference/account-kit/core/functions/cookieToInitialState",
      },
      {
        text: "createAccount",
        link: "/reference/account-kit/core/functions/createAccount",
      },
      {
        text: "createConfig",
        link: "/reference/account-kit/core/functions/createConfig",
      },
      {
        text: "defaultAccountState",
        link: "/reference/account-kit/core/functions/defaultAccountState",
      },
      {
        text: "getAccount",
        link: "/reference/account-kit/core/functions/getAccount",
      },
      {
        text: "getBundlerClient",
        link: "/reference/account-kit/core/functions/getBundlerClient",
      },
      {
        text: "getChain",
        link: "/reference/account-kit/core/functions/getChain",
      },
      {
        text: "getConnection",
        link: "/reference/account-kit/core/functions/getConnection",
      },
      {
        text: "getSigner",
        link: "/reference/account-kit/core/functions/getSigner",
      },
      {
        text: "getSignerStatus",
        link: "/reference/account-kit/core/functions/getSignerStatus",
      },
      {
        text: "getUser",
        link: "/reference/account-kit/core/functions/getUser",
      },
      {
        text: "hydrate",
        link: "/reference/account-kit/core/functions/hydrate",
      },
      {
        text: "reconnect",
        link: "/reference/account-kit/core/functions/reconnect",
      },
      {
        text: "setChain",
        link: "/reference/account-kit/core/functions/setChain",
      },
      {
        text: "watchAccount",
        link: "/reference/account-kit/core/functions/watchAccount",
      },
      {
        text: "watchBundlerClient",
        link: "/reference/account-kit/core/functions/watchBundlerClient",
      },
      {
        text: "watchChain",
        link: "/reference/account-kit/core/functions/watchChain",
      },
      {
        text: "watchConnection",
        link: "/reference/account-kit/core/functions/watchConnection",
      },
      {
        text: "watchSigner",
        link: "/reference/account-kit/core/functions/watchSigner",
      },
      {
        text: "watchSignerStatus",
        link: "/reference/account-kit/core/functions/watchSignerStatus",
      },
      {
        text: "watchUser",
        link: "/reference/account-kit/core/functions/watchUser",
      },
    ],
  },
];
