// This file is autogenerated, see scripts/prebuild.ts
import { SidebarItem } from "vocs";

export const accountKitInfraReferenceSidebar: SidebarItem[] = [
  {
    text: "@account-kit/infra",
    items: [
      {
        text: "Overview",
        link: "/reference/account-kit/infra",
      },
    ],
  },
  {
    text: "Functions",
    items: [
      {
        text: "alchemy",
        link: "/reference/account-kit/infra/functions/alchemy",
      },
      {
        text: "alchemyActions",
        link: "/reference/account-kit/infra/functions/alchemyActions",
      },
      {
        text: "alchemyEnhancedApiActions",
        link: "/reference/account-kit/infra/functions/alchemyEnhancedApiActions",
      },
      {
        text: "alchemyFeeEstimator",
        link: "/reference/account-kit/infra/functions/alchemyFeeEstimator",
      },
      {
        text: "alchemyGasManagerMiddleware",
        link: "/reference/account-kit/infra/functions/alchemyGasManagerMiddleware",
      },
      {
        text: "alchemyUserOperationSimulator",
        link: "/reference/account-kit/infra/functions/alchemyUserOperationSimulator",
      },
      {
        text: "createAlchemyPublicRpcClient",
        link: "/reference/account-kit/infra/functions/createAlchemyPublicRpcClient",
      },
      {
        text: "createAlchemySmartAccountClient",
        link: "/reference/account-kit/infra/functions/createAlchemySmartAccountClient",
      },
      {
        text: "defineAlchemyChain",
        link: "/reference/account-kit/infra/functions/defineAlchemyChain",
      },
      {
        text: "getAlchemyPaymasterAddress",
        link: "/reference/account-kit/infra/functions/getAlchemyPaymasterAddress",
      },
      {
        text: "getDefaultUserOperationFeeOptions",
        link: "/reference/account-kit/infra/functions/getDefaultUserOperationFeeOptions",
      },
      {
        text: "isAlchemySmartAccountClient",
        link: "/reference/account-kit/infra/functions/isAlchemySmartAccountClient",
      },
      {
        text: "isAlchemyTransport",
        link: "/reference/account-kit/infra/functions/isAlchemyTransport",
      },
      {
        text: "simulateUserOperationChanges",
        link: "/reference/account-kit/infra/functions/simulateUserOperationChanges",
      },
    ],
  },
  {
    text: "Resources",
    items: [
      {
        text: "Third Party",
        items: [
          {
            text: "Bundlers",
            link: "/third-party/bundlers",
          },
          {
            text: "Chains",
            link: "/third-party/chains",
          },
          {
            text: "Paymasters",
            link: "/third-party/paymasters",
          },
          {
            text: "Signers",
            link: "/third-party/signers",
          },
          {
            text: "Smart Contracts",
            link: "/third-party/smart-contracts",
          },
        ],
        collapsed: true,
      },
      {
        text: "Terms",
        link: "/resources/terms",
      },
      {
        text: "Types",
        link: "/resources/types",
      },
      {
        text: "FAQs",
        link: "/resources/faqs",
      },
      {
        text: "Contact us",
        link: "/resources/contact-us",
      },
    ],
  },
];
