// This file is autogenerated, see scripts/prebuild.ts
import { SidebarItem } from "vocs";

export const accountKitInfraReferenceSidebar: SidebarItem[] = [
  {
    text: "@account-kit/infra",
    items: [
      {
        text: "Overview",
        link: "/reference/account-kit/infra",
      },
    ],
  },
  {
    text: "Functions",
    items: [
      {
        text: "alchemyActions",
        link: "/reference/account-kit/infra/functions/alchemyActions",
      },
      {
        text: "alchemyEnhancedApiActions",
        link: "/reference/account-kit/infra/functions/alchemyEnhancedApiActions",
      },
      {
        text: "alchemyFeeEstimator",
        link: "/reference/account-kit/infra/functions/alchemyFeeEstimator",
      },
      {
        text: "alchemyGasManagerMiddleware",
        link: "/reference/account-kit/infra/functions/alchemyGasManagerMiddleware",
      },
      {
        text: "alchemyUserOperationSimulator",
        link: "/reference/account-kit/infra/functions/alchemyUserOperationSimulator",
      },
      {
        text: "createAlchemyPublicRpcClient",
        link: "/reference/account-kit/infra/functions/createAlchemyPublicRpcClient",
      },
      {
        text: "createAlchemySmartAccountClient",
        link: "/reference/account-kit/infra/functions/createAlchemySmartAccountClient",
      },
      {
        text: "defineAlchemyChain",
        link: "/reference/account-kit/infra/functions/defineAlchemyChain",
      },
      {
        text: "getAlchemyPaymasterAddress",
        link: "/reference/account-kit/infra/functions/getAlchemyPaymasterAddress",
      },
      {
        text: "getDefaultUserOperationFeeOptions",
        link: "/reference/account-kit/infra/functions/getDefaultUserOperationFeeOptions",
      },
      {
        text: "isAlchemySmartAccountClient",
        link: "/reference/account-kit/infra/functions/isAlchemySmartAccountClient",
      },
      {
        text: "simulateUserOperationChanges",
        link: "/reference/account-kit/infra/functions/simulateUserOperationChanges",
      },
    ],
  },
  {
    text: "Resources",
    items: [
      {
        text: "FAQs",
        link: "/resources/faqs",
      },
      {
        text: "React Native",
        link: "/resources/react-native",
      },
      {
        text: "Terms",
        link: "/resources/terms",
      },
      {
        text: "Types",
        link: "/resources/types",
      },
      {
        text: "Contact us",
        link: "/resources/contact-us",
      },
    ],
  },
];
