// This file is autogenerated, see scripts/prebuild.ts
import { SidebarItem } from "vocs";

export const accountKitInfraReferenceSidebar: SidebarItem[] = [
  {
    text: "@account-kit/infra",
    items: [
      {
        text: "Overview",
        link: "/reference/account-kit/infra",
      },
    ],
  },
  {
    text: "Functions",
    items: [
      {
        text: "alchemy",
        link: "/reference/account-kit/infra/functions/alchemy",
      },
      {
        text: "alchemyActions",
        link: "/reference/account-kit/infra/functions/alchemyActions",
      },
      {
        text: "alchemyEnhancedApiActions",
        link: "/reference/account-kit/infra/functions/alchemyEnhancedApiActions",
      },
      {
        text: "alchemyFeeEstimator",
        link: "/reference/account-kit/infra/functions/alchemyFeeEstimator",
      },
      {
        text: "alchemyGasManagerMiddleware",
        link: "/reference/account-kit/infra/functions/alchemyGasManagerMiddleware",
      },
      {
        text: "alchemyUserOperationSimulator",
        link: "/reference/account-kit/infra/functions/alchemyUserOperationSimulator",
      },
      {
        text: "createAlchemyPublicRpcClient",
        link: "/reference/account-kit/infra/functions/createAlchemyPublicRpcClient",
      },
      {
        text: "createAlchemySmartAccountClient",
        link: "/reference/account-kit/infra/functions/createAlchemySmartAccountClient",
      },
      {
        text: "defineAlchemyChain",
        link: "/reference/account-kit/infra/functions/defineAlchemyChain",
      },
      {
        text: "getAlchemyPaymasterAddress",
        link: "/reference/account-kit/infra/functions/getAlchemyPaymasterAddress",
      },
      {
        text: "getDefaultUserOperationFeeOptions",
        link: "/reference/account-kit/infra/functions/getDefaultUserOperationFeeOptions",
      },
      {
        text: "isAlchemySmartAccountClient",
        link: "/reference/account-kit/infra/functions/isAlchemySmartAccountClient",
      },
      {
        text: "simulateUserOperationChanges",
        link: "/reference/account-kit/infra/functions/simulateUserOperationChanges",
      },
    ],
  },
  {
    text: "Resources",
    items: [
      {
        text: "React Native",
        items: [
          {
            text: "Overview",
            link: "/react-native/overview",
          },
          {
            text: "Getting Started",
            items: [
              {
                text: "Getting started on Expo",
                link: "/react-native/getting-started/getting-started-expo",
              },
              {
                text: "Getting started on Bare React Native",
                link: "/react-native/getting-started/getting-started-rn-bare",
              },
            ],
          },
          {
            text: "Using the Signer",
            items: [
              {
                text: "Overview",
                link: "/react-native/signer/overview",
              },
              {
                text: "Setup",
                link: "/react-native/signer/setup-guide",
              },
              {
                text: "Authenticating Users",
                items: [
                  {
                    text: "Authenticating Users via Magic Link",
                    link: "/react-native/signer/authenticating-users/authenticating-with-magic-link",
                  },
                  {
                    text: "Authenticating Users via One-Time Password (OTP)",
                    link: "/react-native/signer/authenticating-users/authenticating-with-otp",
                  },
                ],
                collapsed: true,
              },
            ],
          },
        ],
        collapsed: true,
      },
      {
        text: "Third Party",
        items: [
          {
            text: "Bundlers",
            link: "/third-party/bundlers",
          },
          {
            text: "Chains",
            link: "/third-party/chains",
          },
          {
            text: "Paymasters",
            link: "/third-party/paymasters",
          },
          {
            text: "Signers",
            link: "/third-party/signers",
          },
          {
            text: "Smart Contracts",
            link: "/third-party/smart-contracts",
          },
        ],
        collapsed: true,
      },
      {
        text: "Terms",
        link: "/resources/terms",
      },
      {
        text: "Types",
        link: "/resources/types",
      },
      {
        text: "FAQs",
        link: "/resources/faqs",
      },
      {
        text: "Contact us",
        link: "/resources/contact-us",
      },
    ],
  },
];
