// This file is autogenerated, see scripts/prebuild.ts
import { SidebarItem } from "vocs";

export const accountKitReactReferenceSidebar: SidebarItem[] = [
  {
    text: "@account-kit/react",
    items: [
      {
        text: "Overview",
        link: "/reference/account-kit/react",
      },
    ],
  },
  {
    text: "Functions",
    items: [
      {
        text: "useAccount",
        link: "/reference/account-kit/react/functions/useAccount",
      },
      {
        text: "useAddPasskey",
        link: "/reference/account-kit/react/functions/useAddPasskey",
      },
      {
        text: "useAuthError",
        link: "/reference/account-kit/react/functions/useAuthError",
      },
      {
        text: "useAuthModal",
        link: "/reference/account-kit/react/functions/useAuthModal",
      },
      {
        text: "useAuthenticate",
        link: "/reference/account-kit/react/functions/useAuthenticate",
      },
      {
        text: "useBundlerClient",
        link: "/reference/account-kit/react/functions/useBundlerClient",
      },
      {
        text: "useChain",
        link: "/reference/account-kit/react/functions/useChain",
      },
      {
        text: "useClientActions",
        link: "/reference/account-kit/react/functions/useClientActions",
      },
      {
        text: "useDropAndReplaceUserOperation",
        link: "/reference/account-kit/react/functions/useDropAndReplaceUserOperation",
      },
      {
        text: "useExportAccount",
        link: "/reference/account-kit/react/functions/useExportAccount",
      },
      {
        text: "useLogout",
        link: "/reference/account-kit/react/functions/useLogout",
      },
      {
        text: "useSendTransaction",
        link: "/reference/account-kit/react/functions/useSendTransaction",
      },
      {
        text: "useSendTransactions",
        link: "/reference/account-kit/react/functions/useSendTransactions",
      },
      {
        text: "useSendUserOperation",
        link: "/reference/account-kit/react/functions/useSendUserOperation",
      },
      {
        text: "useSignMessage",
        link: "/reference/account-kit/react/functions/useSignMessage",
      },
      {
        text: "useSignTypedData",
        link: "/reference/account-kit/react/functions/useSignTypedData",
      },
      {
        text: "useSigner",
        link: "/reference/account-kit/react/functions/useSigner",
      },
      {
        text: "useSignerStatus",
        link: "/reference/account-kit/react/functions/useSignerStatus",
      },
      {
        text: "useSmartAccountClient",
        link: "/reference/account-kit/react/functions/useSmartAccountClient",
      },
      {
        text: "useUser",
        link: "/reference/account-kit/react/functions/useUser",
      },
      {
        text: "useWaitForUserOperationTransaction",
        link: "/reference/account-kit/react/functions/useWaitForUserOperationTransaction",
      },
    ],
  },
];
