// This file is autogenerated, see scripts/prebuild.ts
import { SidebarItem } from "vocs";

export const accountKitReactNativeReferenceSidebar: SidebarItem[] = [
  {
    text: "@account-kit/react-native",
    items: [
      {
        text: "Overview",
        link: "/reference/account-kit/react-native",
      },
    ],
  },
  {
    text: "Functions",
    items: [
      {
        text: "RNAlchemySigner",
        link: "/reference/account-kit/react-native/functions/RNAlchemySigner",
      },
      {
        text: "createConfig",
        link: "/reference/account-kit/react-native/functions/createConfig",
      },
    ],
  },
  {
    text: "Resources",
    items: [
      {
        text: "Third Party",
        items: [
          {
            text: "Bundlers",
            link: "/third-party/bundlers",
          },
          {
            text: "Chains",
            link: "/third-party/chains",
          },
          {
            text: "Paymasters",
            link: "/third-party/paymasters",
          },
          {
            text: "Signers",
            link: "/third-party/signers",
          },
          {
            text: "Smart Contracts",
            link: "/third-party/smart-contracts",
          },
        ],
        collapsed: true,
      },
      {
        text: "Terms",
        link: "/resources/terms",
      },
      {
        text: "Types",
        link: "/resources/types",
      },
      {
        text: "FAQs",
        link: "/resources/faqs",
      },
      {
        text: "Contact us",
        link: "/resources/contact-us",
      },
    ],
  },
];
