// This file is autogenerated, see scripts/prebuild.ts
import { SidebarItem } from "vocs";

export const accountKitSmartContractsReferenceSidebar: SidebarItem[] = [
  {
    text: "@account-kit/smart-contracts",
    items: [
      {
        text: "Overview",
        link: "/reference/account-kit/smart-contracts",
      },
    ],
  },
  {
    text: "Functions",
    items: [
      {
        text: "accountLoupeActions",
        link: "/reference/account-kit/smart-contracts/functions/accountLoupeActions",
      },
      {
        text: "buildSessionKeysToRemoveStruct",
        link: "/reference/account-kit/smart-contracts/functions/buildSessionKeysToRemoveStruct",
      },
      {
        text: "combineSignatures",
        link: "/reference/account-kit/smart-contracts/functions/combineSignatures",
      },
      {
        text: "createLightAccount",
        link: "/reference/account-kit/smart-contracts/functions/createLightAccount",
      },
      {
        text: "createLightAccountAlchemyClient",
        link: "/reference/account-kit/smart-contracts/functions/createLightAccountAlchemyClient",
      },
      {
        text: "createLightAccountClient",
        link: "/reference/account-kit/smart-contracts/functions/createLightAccountClient",
      },
      {
        text: "createModularAccountAlchemyClient",
        link: "/reference/account-kit/smart-contracts/functions/createModularAccountAlchemyClient",
      },
      {
        text: "createMultiOwnerLightAccount",
        link: "/reference/account-kit/smart-contracts/functions/createMultiOwnerLightAccount",
      },
      {
        text: "createMultiOwnerLightAccountAlchemyClient",
        link: "/reference/account-kit/smart-contracts/functions/createMultiOwnerLightAccountAlchemyClient",
      },
      {
        text: "createMultiOwnerLightAccountClient",
        link: "/reference/account-kit/smart-contracts/functions/createMultiOwnerLightAccountClient",
      },
      {
        text: "createMultiOwnerModularAccount",
        link: "/reference/account-kit/smart-contracts/functions/createMultiOwnerModularAccount",
      },
      {
        text: "createMultiOwnerModularAccountClient",
        link: "/reference/account-kit/smart-contracts/functions/createMultiOwnerModularAccountClient",
      },
      {
        text: "createMultisigAccountAlchemyClient",
        link: "/reference/account-kit/smart-contracts/functions/createMultisigAccountAlchemyClient",
      },
      {
        text: "createMultisigModularAccount",
        link: "/reference/account-kit/smart-contracts/functions/createMultisigModularAccount",
      },
      {
        text: "createMultisigModularAccountClient",
        link: "/reference/account-kit/smart-contracts/functions/createMultisigModularAccountClient",
      },
      {
        text: "defaultLightAccountVersion",
        link: "/reference/account-kit/smart-contracts/functions/defaultLightAccountVersion",
      },
      {
        text: "formatSignatures",
        link: "/reference/account-kit/smart-contracts/functions/formatSignatures",
      },
      {
        text: "getDefaultLightAccountFactoryAddress",
        link: "/reference/account-kit/smart-contracts/functions/getDefaultLightAccountFactoryAddress",
      },
      {
        text: "getDefaultMultiOwnerLightAccountFactoryAddress",
        link: "/reference/account-kit/smart-contracts/functions/getDefaultMultiOwnerLightAccountFactoryAddress",
      },
      {
        text: "getDefaultMultiOwnerModularAccountFactoryAddress",
        link: "/reference/account-kit/smart-contracts/functions/getDefaultMultiOwnerModularAccountFactoryAddress",
      },
      {
        text: "getDefaultMultisigModularAccountFactoryAddress",
        link: "/reference/account-kit/smart-contracts/functions/getDefaultMultisigModularAccountFactoryAddress",
      },
      {
        text: "getLightAccountVersionForAccount",
        link: "/reference/account-kit/smart-contracts/functions/getLightAccountVersionForAccount",
      },
      {
        text: "getMAInitializationData",
        link: "/reference/account-kit/smart-contracts/functions/getMAInitializationData",
      },
      {
        text: "getMSCAUpgradeToData",
        link: "/reference/account-kit/smart-contracts/functions/getMSCAUpgradeToData",
      },
      {
        text: "getSignerType",
        link: "/reference/account-kit/smart-contracts/functions/getSignerType",
      },
      {
        text: "installPlugin",
        link: "/reference/account-kit/smart-contracts/functions/installPlugin",
      },
      {
        text: "lightAccountClientActions",
        link: "/reference/account-kit/smart-contracts/functions/lightAccountClientActions",
      },
      {
        text: "multiOwnerLightAccountClientActions",
        link: "/reference/account-kit/smart-contracts/functions/multiOwnerLightAccountClientActions",
      },
      {
        text: "multiOwnerPluginActions",
        link: "/reference/account-kit/smart-contracts/functions/multiOwnerPluginActions",
      },
      {
        text: "multisigPluginActions",
        link: "/reference/account-kit/smart-contracts/functions/multisigPluginActions",
      },
      {
        text: "multisigSignatureMiddleware",
        link: "/reference/account-kit/smart-contracts/functions/multisigSignatureMiddleware",
      },
      {
        text: "pluginManagerActions",
        link: "/reference/account-kit/smart-contracts/functions/pluginManagerActions",
      },
      {
        text: "sessionKeyPluginActions",
        link: "/reference/account-kit/smart-contracts/functions/sessionKeyPluginActions",
      },
      {
        text: "splitAggregatedSignature",
        link: "/reference/account-kit/smart-contracts/functions/splitAggregatedSignature",
      },
    ],
  },
  {
    text: "Classes",
    items: [
      {
        text: "SessionKeyPermissionsBuilder",
        items: [
          {
            text: "addContractAddressAccessEntry",
            link: "/reference/account-kit/smart-contracts/classes/SessionKeyPermissionsBuilder/addContractAddressAccessEntry",
          },
          {
            text: "addContractFunctionAccessEntry",
            link: "/reference/account-kit/smart-contracts/classes/SessionKeyPermissionsBuilder/addContractFunctionAccessEntry",
          },
          {
            text: "addErc20TokenSpendLimit",
            link: "/reference/account-kit/smart-contracts/classes/SessionKeyPermissionsBuilder/addErc20TokenSpendLimit",
          },
          {
            text: "encode",
            link: "/reference/account-kit/smart-contracts/classes/SessionKeyPermissionsBuilder/encode",
          },
          {
            text: "setContractAccessControlType",
            link: "/reference/account-kit/smart-contracts/classes/SessionKeyPermissionsBuilder/setContractAccessControlType",
          },
          {
            text: "setGasSpendLimit",
            link: "/reference/account-kit/smart-contracts/classes/SessionKeyPermissionsBuilder/setGasSpendLimit",
          },
          {
            text: "setNativeTokenSpendLimit",
            link: "/reference/account-kit/smart-contracts/classes/SessionKeyPermissionsBuilder/setNativeTokenSpendLimit",
          },
          {
            text: "setRequiredPaymaster",
            link: "/reference/account-kit/smart-contracts/classes/SessionKeyPermissionsBuilder/setRequiredPaymaster",
          },
          {
            text: "setTimeRange",
            link: "/reference/account-kit/smart-contracts/classes/SessionKeyPermissionsBuilder/setTimeRange",
          },
        ],
      },
      {
        text: "SessionKeySigner",
        items: [
          {
            text: "constructor",
            link: "/reference/account-kit/smart-contracts/classes/SessionKeySigner/constructor",
          },
          {
            text: "generateNewKey",
            link: "/reference/account-kit/smart-contracts/classes/SessionKeySigner/generateNewKey",
          },
          {
            text: "getAddress",
            link: "/reference/account-kit/smart-contracts/classes/SessionKeySigner/getAddress",
          },
          {
            text: "signMessage",
            link: "/reference/account-kit/smart-contracts/classes/SessionKeySigner/signMessage",
          },
          {
            text: "signTypedData",
            link: "/reference/account-kit/smart-contracts/classes/SessionKeySigner/signTypedData",
          },
        ],
      },
    ],
  },
  {
    text: "Resources",
    items: [
      {
        text: "React Native",
        items: [
          {
            text: "Overview",
            link: "/react-native/overview",
          },
          {
            text: "Getting Started",
            link: "/react-native/getting-started",
          },
          {
            text: "React Native Signer",
            items: [
              {
                text: "Overview",
                link: "/react-native/signer/overview",
              },
              {
                text: "Configuration Guide",
                link: "/react-native/signer/configuration-guide",
              },
              {
                text: "Expo Installation",
                link: "/react-native/signer/expo-installation",
              },
              {
                text: "Bare React Native Installation",
                link: "/react-native/signer/bare-installation",
              },
            ],
          },
        ],
        collapsed: true,
      },
      {
        text: "Third Party",
        items: [
          {
            text: "Bundlers",
            link: "/third-party/bundlers",
          },
          {
            text: "Chains",
            link: "/third-party/chains",
          },
          {
            text: "Paymasters",
            link: "/third-party/paymasters",
          },
          {
            text: "Signers",
            link: "/third-party/signers",
          },
          {
            text: "Smart Contracts",
            link: "/third-party/smart-contracts",
          },
        ],
        collapsed: true,
      },
      {
        text: "Terms",
        link: "/resources/terms",
      },
      {
        text: "Types",
        link: "/resources/types",
      },
      {
        text: "FAQs",
        link: "/resources/faqs",
      },
      {
        text: "Contact us",
        link: "/resources/contact-us",
      },
    ],
  },
];
