import { encodeAbiParameters } from "viem";
import { installPlugin as installPlugin_ } from "../../plugin-manager/installPlugin.js";
import type { InjectedHook } from "../../plugin-manager/types.js";
import type { FunctionReference } from "../../account-loupe/types.js";
import { type Address, type GetFunctionArgs, encodeFunctionData } from "viem";
import type { Plugin } from "../types";
import type { IMSCA } from "../../types";
import type {
  ISmartAccountProvider,
  SupportedTransports,
  UserOperationOverrides,
} from "@alchemy/aa-core";

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// ERC6900PluginGen: This file is auto-generated by plugingen
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

type InstallArgs = [];
export type InstallTokenReceiverPluginParams = {
  args: Parameters<typeof encodeAbiParameters<InstallArgs>>[1];
  pluginAddress?: Address;
  injectedHooks?: InjectedHook[];
  dependencyOverrides?: FunctionReference[];
};

const TokenReceiverPlugin_ = {
  meta: {
    name: "Token Receiver Plugin",
    version: "1.0.0",
    addresses: {
      11155111: "0xa81C0AEaB22b21b4da8d8728063f6570384b48C9" as Address,
    } as Record<number, Address>,
  },
  accountMethods: (_account: IMSCA<any, any>) => ({
    encodeTokensReceivedData: ({
      args,
    }: GetFunctionArgs<
      typeof TokenReceiverPluginExecutionFunctionAbi,
      "tokensReceived"
    >) => {
      return encodeFunctionData({
        abi: TokenReceiverPluginExecutionFunctionAbi,
        functionName: "tokensReceived",
        args,
      });
    },

    encodeOnErc721ReceivedData: ({
      args,
    }: GetFunctionArgs<
      typeof TokenReceiverPluginExecutionFunctionAbi,
      "onERC721Received"
    >) => {
      return encodeFunctionData({
        abi: TokenReceiverPluginExecutionFunctionAbi,
        functionName: "onERC721Received",
        args,
      });
    },

    encodeOnErc1155ReceivedData: ({
      args,
    }: GetFunctionArgs<
      typeof TokenReceiverPluginExecutionFunctionAbi,
      "onERC1155Received"
    >) => {
      return encodeFunctionData({
        abi: TokenReceiverPluginExecutionFunctionAbi,
        functionName: "onERC1155Received",
        args,
      });
    },

    encodeOnErc1155BatchReceivedData: ({
      args,
    }: GetFunctionArgs<
      typeof TokenReceiverPluginExecutionFunctionAbi,
      "onERC1155BatchReceived"
    >) => {
      return encodeFunctionData({
        abi: TokenReceiverPluginExecutionFunctionAbi,
        functionName: "onERC1155BatchReceived",
        args,
      });
    },
  }),
  providerMethods: <
    TTransport extends SupportedTransports,
    P extends ISmartAccountProvider<TTransport> & {
      account: IMSCA<TTransport>;
    }
  >(
    provider: P
  ) => ({
    tokensReceived: (
      {
        args,
      }: GetFunctionArgs<
        typeof TokenReceiverPluginExecutionFunctionAbi,
        "tokensReceived"
      >,
      overrides?: UserOperationOverrides
    ) => {
      const callData = encodeFunctionData({
        abi: TokenReceiverPluginExecutionFunctionAbi,
        functionName: "tokensReceived",
        args,
      });

      return provider.sendUserOperation(callData, overrides);
    },

    onErc721Received: (
      {
        args,
      }: GetFunctionArgs<
        typeof TokenReceiverPluginExecutionFunctionAbi,
        "onERC721Received"
      >,
      overrides?: UserOperationOverrides
    ) => {
      const callData = encodeFunctionData({
        abi: TokenReceiverPluginExecutionFunctionAbi,
        functionName: "onERC721Received",
        args,
      });

      return provider.sendUserOperation(callData, overrides);
    },

    onErc1155Received: (
      {
        args,
      }: GetFunctionArgs<
        typeof TokenReceiverPluginExecutionFunctionAbi,
        "onERC1155Received"
      >,
      overrides?: UserOperationOverrides
    ) => {
      const callData = encodeFunctionData({
        abi: TokenReceiverPluginExecutionFunctionAbi,
        functionName: "onERC1155Received",
        args,
      });

      return provider.sendUserOperation(callData, overrides);
    },

    onErc1155BatchReceived: (
      {
        args,
      }: GetFunctionArgs<
        typeof TokenReceiverPluginExecutionFunctionAbi,
        "onERC1155BatchReceived"
      >,
      overrides?: UserOperationOverrides
    ) => {
      const callData = encodeFunctionData({
        abi: TokenReceiverPluginExecutionFunctionAbi,
        functionName: "onERC1155BatchReceived",
        args,
      });

      return provider.sendUserOperation(callData, overrides);
    },

    installTokenReceiverPlugin: (
      params: InstallTokenReceiverPluginParams,
      overrides?: UserOperationOverrides
    ) => {
      const chain = provider.rpcClient.chain;
      const dependencies = params.dependencyOverrides ?? [];
      const pluginAddress =
        params.pluginAddress ??
        (TokenReceiverPlugin_.meta.addresses[chain.id] as Address | undefined);

      if (!pluginAddress) {
        throw new Error(
          "missing TokenReceiverPlugin address for chain " + chain.name
        );
      }

      return installPlugin_(
        provider,
        {
          pluginAddress,
          pluginInitData: encodeAbiParameters([], params.args),
          dependencies,
        },
        overrides
      );
    },
  }),
};

export const TokenReceiverPlugin: Plugin<
  ReturnType<(typeof TokenReceiverPlugin_)["accountMethods"]>,
  ReturnType<(typeof TokenReceiverPlugin_)["providerMethods"]>
> = TokenReceiverPlugin_;

export const TokenReceiverPluginExecutionFunctionAbi = [
  {
    stateMutability: "pure",
    type: "function",
    inputs: [
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "uint256", type: "uint256" },
      { name: "", internalType: "bytes", type: "bytes" },
      { name: "", internalType: "bytes", type: "bytes" },
    ],
    name: "tokensReceived",
    outputs: [],
  },
  {
    stateMutability: "pure",
    type: "function",
    inputs: [
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "uint256", type: "uint256" },
      { name: "", internalType: "bytes", type: "bytes" },
    ],
    name: "onERC721Received",
    outputs: [{ name: "", internalType: "bytes4", type: "bytes4" }],
  },
  {
    stateMutability: "pure",
    type: "function",
    inputs: [
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "uint256", type: "uint256" },
      { name: "", internalType: "uint256", type: "uint256" },
      { name: "", internalType: "bytes", type: "bytes" },
    ],
    name: "onERC1155Received",
    outputs: [{ name: "", internalType: "bytes4", type: "bytes4" }],
  },
  {
    stateMutability: "pure",
    type: "function",
    inputs: [
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "uint256[]", type: "uint256[]" },
      { name: "", internalType: "uint256[]", type: "uint256[]" },
      { name: "", internalType: "bytes", type: "bytes" },
    ],
    name: "onERC1155BatchReceived",
    outputs: [{ name: "", internalType: "bytes4", type: "bytes4" }],
  },
] as const;
