---
title: useConnection
description: Overview of the useConnection hook
slug: wallets/reference/account-kit/react-native/hooks/useConnection
layout: reference
---

{/* This file is auto-generated by TypeDoc. Do not edit manually. */}

```ts
function useConnection(): Connection;
```

Defined in: account-kit/react/dist/types/hooks/useConnection.d.ts:7

A [hook](https://github.com/alchemyplatform/aa-sdk/blob/main/account-kit/react/src/hooks/useConnection.ts) that returns the current connection including chain, policy, and transport that you’re currently using.

## Returns

`Connection`

the current connection. [ref](https://github.com/alchemyplatform/aa-sdk/blob/main/account-kit/core/src/types.ts#L56)
