import prettier from "prettier";

const BANNER = `/* eslint-disable -- machine-generated file */
// AUTO-GENERATED by @alchemy/api-codegen — DO NOT EDIT.
// Regenerate with \`pnpm generate\`. Spec provenance (docs repo commit + checksums)
// is recorded in api-codegen/specs/specs.lock.json.

`;

/**
 * Prepends the do-not-edit banner and formats generated TypeScript with the
 * repo's prettier config (resolved from the output file's location, exactly
 * as `prettier --write` would). Generated files are excluded from lint, so
 * the generator is responsible for producing stable, formatted output.
 *
 * @param {string} source Generated TypeScript source (without banner)
 * @param {string} outputPath Absolute output path used to resolve prettier config
 * @returns {Promise<string>} Banner + formatted source
 */
export async function formatGenerated(
  source: string,
  outputPath: string,
): Promise<string> {
  const config = await prettier.resolveConfig(outputPath);
  return prettier.format(BANNER + source, {
    ...config,
    parser: "typescript",
  });
}
