// Generated by @alchemy/api-codegen from the docs repo's bundled OpenAPI
// specs (see src/generated/). Re-exported here so the public import path is
// stable regardless of how generation is organized internally.
export type { NftRestSchema } from "../generated/rest/nft.schema.js";
export type { PortfolioRestSchema } from "../generated/rest/portfolio.schema.js";
export type { PricesRestSchema } from "../generated/rest/prices.schema.js";
