import type { TokenRpcSchema } from "../generated/rpc/token.js";
import type {
  AlchemyGetAssetTransfersParams,
  TransfersRpcSchema,
} from "../generated/rpc/transfers.js";
import type { GetAssetTransfersResult } from "../types.js";

// Params/result internals are generated by @alchemy/api-codegen from the docs
// repo's bundled OpenRPC specs (see src/generated/rpc/).

export type GetAssetTransfersRpcParams = AlchemyGetAssetTransfersParams;

/**
 * viem RpcSchema entries for the Data JSON-RPC methods. Attach to a client to
 * get typed `client.request({ method: "alchemy_getAssetTransfers", ... })`.
 *
 * The transfers ReturnType uses the SDK's {@link GetAssetTransfersResult},
 * which collapses the spec's "Not Found (null)" string branch (a docs-spec
 * artifact).
 */
export type DataRpcSchema = [
  {
    Method: TransfersRpcSchema[0]["Method"];
    Parameters: TransfersRpcSchema[0]["Parameters"];
    ReturnType: GetAssetTransfersResult;
  },
  ...TokenRpcSchema,
];
