// This file is autogenerated, see scripts/prebuild.ts
import { SidebarItem } from "vocs";

export const aaSdkCoreReferenceSidebar: SidebarItem[] = [
  {
    text: "@aa-sdk/core",
    items: [
      {
        text: "Overview",
        link: "/reference/aa-sdk/core",
      },
    ],
  },
  {
    text: "Functions",
    items: [
      {
        text: "allEqual",
        link: "/reference/aa-sdk/core/functions/allEqual",
      },
      {
        text: "asyncPipe",
        link: "/reference/aa-sdk/core/functions/asyncPipe",
      },
      {
        text: "buildUserOperation",
        link: "/reference/aa-sdk/core/functions/buildUserOperation",
      },
      {
        text: "buildUserOperationFromTx",
        link: "/reference/aa-sdk/core/functions/buildUserOperationFromTx",
      },
      {
        text: "buildUserOperationFromTxs",
        link: "/reference/aa-sdk/core/functions/buildUserOperationFromTxs",
      },
      {
        text: "bundlerActions",
        link: "/reference/aa-sdk/core/functions/bundlerActions",
      },
      {
        text: "checkGasSponsorshipEligibility",
        link: "/reference/aa-sdk/core/functions/checkGasSponsorshipEligibility",
      },
      {
        text: "convertChainIdToCoinType",
        link: "/reference/aa-sdk/core/functions/convertChainIdToCoinType",
      },
      {
        text: "convertCoinTypeToChain",
        link: "/reference/aa-sdk/core/functions/convertCoinTypeToChain",
      },
      {
        text: "convertCoinTypeToChainId",
        link: "/reference/aa-sdk/core/functions/convertCoinTypeToChainId",
      },
      {
        text: "createBundlerClient",
        link: "/reference/aa-sdk/core/functions/createBundlerClient",
      },
      {
        text: "createBundlerClientFromExisting",
        link: "/reference/aa-sdk/core/functions/createBundlerClientFromExisting",
      },
      {
        text: "createSmartAccountClient",
        link: "/reference/aa-sdk/core/functions/createSmartAccountClient",
      },
      {
        text: "createSmartAccountClientFromExisting",
        link: "/reference/aa-sdk/core/functions/createSmartAccountClientFromExisting",
      },
      {
        text: "deepHexlify",
        link: "/reference/aa-sdk/core/functions/deepHexlify",
      },
      {
        text: "default7702GasEstimator",
        link: "/reference/aa-sdk/core/functions/default7702GasEstimator",
      },
      {
        text: "default7702UserOpSigner",
        link: "/reference/aa-sdk/core/functions/default7702UserOpSigner",
      },
      {
        text: "defaultFeeEstimator",
        link: "/reference/aa-sdk/core/functions/defaultFeeEstimator",
      },
      {
        text: "defaultGasEstimator",
        link: "/reference/aa-sdk/core/functions/defaultGasEstimator",
      },
      {
        text: "defaultPaymasterAndData",
        link: "/reference/aa-sdk/core/functions/defaultPaymasterAndData",
      },
      {
        text: "defaultUserOpSigner",
        link: "/reference/aa-sdk/core/functions/defaultUserOpSigner",
      },
      {
        text: "dropAndReplaceUserOperation",
        link: "/reference/aa-sdk/core/functions/dropAndReplaceUserOperation",
      },
      {
        text: "erc7677Middleware",
        link: "/reference/aa-sdk/core/functions/erc7677Middleware",
      },
      {
        text: "filterUndefined",
        link: "/reference/aa-sdk/core/functions/filterUndefined",
      },
      {
        text: "getAccountAddress",
        link: "/reference/aa-sdk/core/functions/getAccountAddress",
      },
      {
        text: "getEntryPoint",
        link: "/reference/aa-sdk/core/functions/getEntryPoint",
      },
      {
        text: "isEntryPointVersion",
        link: "/reference/aa-sdk/core/functions/isEntryPointVersion",
      },
      {
        text: "isSigner",
        link: "/reference/aa-sdk/core/functions/isSigner",
      },
      {
        text: "isSmartAccountClient",
        link: "/reference/aa-sdk/core/functions/isSmartAccountClient",
      },
      {
        text: "isSmartAccountWithSigner",
        link: "/reference/aa-sdk/core/functions/isSmartAccountWithSigner",
      },
      {
        text: "middlewareActions",
        link: "/reference/aa-sdk/core/functions/middlewareActions",
      },
      {
        text: "noopMiddleware",
        link: "/reference/aa-sdk/core/functions/noopMiddleware",
      },
      {
        text: "parseFactoryAddressFromAccountInitCode",
        link: "/reference/aa-sdk/core/functions/parseFactoryAddressFromAccountInitCode",
      },
      {
        text: "pick",
        link: "/reference/aa-sdk/core/functions/pick",
      },
      {
        text: "resolveProperties",
        link: "/reference/aa-sdk/core/functions/resolveProperties",
      },
      {
        text: "sendTransaction",
        link: "/reference/aa-sdk/core/functions/sendTransaction",
      },
      {
        text: "sendTransactions",
        link: "/reference/aa-sdk/core/functions/sendTransactions",
      },
      {
        text: "sendUserOperation",
        link: "/reference/aa-sdk/core/functions/sendUserOperation",
      },
      {
        text: "smartAccountClientActions",
        link: "/reference/aa-sdk/core/functions/smartAccountClientActions",
      },
      {
        text: "split",
        link: "/reference/aa-sdk/core/functions/split",
      },
      {
        text: "toRecord",
        link: "/reference/aa-sdk/core/functions/toRecord",
      },
      {
        text: "toSmartContractAccount",
        link: "/reference/aa-sdk/core/functions/toSmartContractAccount",
      },
      {
        text: "waitForUserOperationTransaction",
        link: "/reference/aa-sdk/core/functions/waitForUserOperationTransaction",
      },
      {
        text: "wrapSignatureWith6492",
        link: "/reference/aa-sdk/core/functions/wrapSignatureWith6492",
      },
    ],
  },
  {
    text: "Classes",
    items: [
      {
        text: "AccountNotFoundError",
        items: [
          {
            text: "constructor",
            link: "/reference/aa-sdk/core/classes/AccountNotFoundError/constructor",
          },
        ],
      },
      {
        text: "AccountRequiresOwnerError",
        items: [
          {
            text: "constructor",
            link: "/reference/aa-sdk/core/classes/AccountRequiresOwnerError/constructor",
          },
        ],
      },
      {
        text: "BatchExecutionNotSupportedError",
        items: [
          {
            text: "constructor",
            link: "/reference/aa-sdk/core/classes/BatchExecutionNotSupportedError/constructor",
          },
        ],
      },
      {
        text: "ChainNotFoundError",
        items: [
          {
            text: "constructor",
            link: "/reference/aa-sdk/core/classes/ChainNotFoundError/constructor",
          },
        ],
      },
      {
        text: "DefaultFactoryNotDefinedError",
        items: [
          {
            text: "constructor",
            link: "/reference/aa-sdk/core/classes/DefaultFactoryNotDefinedError/constructor",
          },
        ],
      },
      {
        text: "EntityIdOverrideError",
        items: [
          {
            text: "constructor",
            link: "/reference/aa-sdk/core/classes/EntityIdOverrideError/constructor",
          },
        ],
      },
      {
        text: "EntryPointNotFoundError",
        items: [
          {
            text: "constructor",
            link: "/reference/aa-sdk/core/classes/EntryPointNotFoundError/constructor",
          },
        ],
      },
      {
        text: "FailedToFindTransactionError",
        items: [
          {
            text: "constructor",
            link: "/reference/aa-sdk/core/classes/FailedToFindTransactionError/constructor",
          },
        ],
      },
      {
        text: "FailedToGetStorageSlotError",
        items: [
          {
            text: "constructor",
            link: "/reference/aa-sdk/core/classes/FailedToGetStorageSlotError/constructor",
          },
        ],
      },
      {
        text: "GetCounterFactualAddressError",
        items: [
          {
            text: "constructor",
            link: "/reference/aa-sdk/core/classes/GetCounterFactualAddressError/constructor",
          },
        ],
      },
      {
        text: "IncompatibleClientError",
        items: [
          {
            text: "constructor",
            link: "/reference/aa-sdk/core/classes/IncompatibleClientError/constructor",
          },
        ],
      },
      {
        text: "IncorrectAccountType",
        items: [
          {
            text: "constructor",
            link: "/reference/aa-sdk/core/classes/IncorrectAccountType/constructor",
          },
        ],
      },
      {
        text: "InvalidEntityIdError",
        items: [
          {
            text: "constructor",
            link: "/reference/aa-sdk/core/classes/InvalidEntityIdError/constructor",
          },
        ],
      },
      {
        text: "InvalidEntryPointError",
        items: [
          {
            text: "constructor",
            link: "/reference/aa-sdk/core/classes/InvalidEntryPointError/constructor",
          },
        ],
      },
      {
        text: "InvalidModularAccountV2Mode",
        items: [
          {
            text: "constructor",
            link: "/reference/aa-sdk/core/classes/InvalidModularAccountV2Mode/constructor",
          },
        ],
      },
      {
        text: "InvalidNonceKeyError",
        items: [
          {
            text: "constructor",
            link: "/reference/aa-sdk/core/classes/InvalidNonceKeyError/constructor",
          },
        ],
      },
      {
        text: "InvalidRpcUrlError",
        items: [
          {
            text: "constructor",
            link: "/reference/aa-sdk/core/classes/InvalidRpcUrlError/constructor",
          },
        ],
      },
      {
        text: "InvalidSignerTypeError",
        items: [
          {
            text: "constructor",
            link: "/reference/aa-sdk/core/classes/InvalidSignerTypeError/constructor",
          },
        ],
      },
      {
        text: "InvalidUserOperationError",
        items: [
          {
            text: "constructor",
            link: "/reference/aa-sdk/core/classes/InvalidUserOperationError/constructor",
          },
        ],
      },
      {
        text: "LocalAccountSigner",
        items: [
          {
            text: "constructor",
            link: "/reference/aa-sdk/core/classes/LocalAccountSigner/constructor",
          },
          {
            text: "generatePrivateKeySigner",
            link: "/reference/aa-sdk/core/classes/LocalAccountSigner/generatePrivateKeySigner",
          },
          {
            text: "getAddress",
            link: "/reference/aa-sdk/core/classes/LocalAccountSigner/getAddress",
          },
          {
            text: "mnemonicToAccountSigner",
            link: "/reference/aa-sdk/core/classes/LocalAccountSigner/mnemonicToAccountSigner",
          },
          {
            text: "privateKeyToAccountSigner",
            link: "/reference/aa-sdk/core/classes/LocalAccountSigner/privateKeyToAccountSigner",
          },
          {
            text: "signAuthorization",
            link: "/reference/aa-sdk/core/classes/LocalAccountSigner/signAuthorization",
          },
          {
            text: "signMessage",
            link: "/reference/aa-sdk/core/classes/LocalAccountSigner/signMessage",
          },
          {
            text: "signTypedData",
            link: "/reference/aa-sdk/core/classes/LocalAccountSigner/signTypedData",
          },
        ],
      },
      {
        text: "Logger",
        items: [
          {
            text: "debug",
            link: "/reference/aa-sdk/core/classes/Logger/debug",
          },
          {
            text: "error",
            link: "/reference/aa-sdk/core/classes/Logger/error",
          },
          {
            text: "info",
            link: "/reference/aa-sdk/core/classes/Logger/info",
          },
          {
            text: "setLogFilter",
            link: "/reference/aa-sdk/core/classes/Logger/setLogFilter",
          },
          {
            text: "setLogLevel",
            link: "/reference/aa-sdk/core/classes/Logger/setLogLevel",
          },
          {
            text: "verbose",
            link: "/reference/aa-sdk/core/classes/Logger/verbose",
          },
          {
            text: "warn",
            link: "/reference/aa-sdk/core/classes/Logger/warn",
          },
        ],
      },
      {
        text: "SignTransactionNotSupportedError",
        items: [
          {
            text: "constructor",
            link: "/reference/aa-sdk/core/classes/SignTransactionNotSupportedError/constructor",
          },
        ],
      },
      {
        text: "SmartAccountWithSignerRequiredError",
        items: [
          {
            text: "constructor",
            link: "/reference/aa-sdk/core/classes/SmartAccountWithSignerRequiredError/constructor",
          },
        ],
      },
      {
        text: "TransactionMissingToParamError",
        items: [
          {
            text: "constructor",
            link: "/reference/aa-sdk/core/classes/TransactionMissingToParamError/constructor",
          },
        ],
      },
      {
        text: "UpgradeToAndCallNotSupportedError",
        items: [
          {
            text: "constructor",
            link: "/reference/aa-sdk/core/classes/UpgradeToAndCallNotSupportedError/constructor",
          },
        ],
      },
      {
        text: "UpgradesNotSupportedError",
        items: [
          {
            text: "constructor",
            link: "/reference/aa-sdk/core/classes/UpgradesNotSupportedError/constructor",
          },
        ],
      },
      {
        text: "WaitForUserOperationError",
        items: [
          {
            text: "constructor",
            link: "/reference/aa-sdk/core/classes/WaitForUserOperationError/constructor",
          },
        ],
      },
      {
        text: "WalletClientSigner",
        items: [
          {
            text: "constructor",
            link: "/reference/aa-sdk/core/classes/WalletClientSigner/constructor",
          },
          {
            text: "getAddress",
            link: "/reference/aa-sdk/core/classes/WalletClientSigner/getAddress",
          },
          {
            text: "signMessage",
            link: "/reference/aa-sdk/core/classes/WalletClientSigner/signMessage",
          },
          {
            text: "signTypedData",
            link: "/reference/aa-sdk/core/classes/WalletClientSigner/signTypedData",
          },
        ],
      },
    ],
  },
  {
    text: "Resources",
    items: [
      {
        text: "Third Party",
        items: [
          {
            text: "Bundlers",
            link: "/third-party/bundlers",
          },
          {
            text: "Chains",
            link: "/third-party/chains",
          },
          {
            text: "Paymasters",
            link: "/third-party/paymasters",
          },
          {
            text: "Signers",
            link: "/third-party/signers",
          },
          {
            text: "Smart Contracts",
            link: "/third-party/smart-contracts",
          },
        ],
        collapsed: true,
      },
      {
        text: "Terms",
        link: "/resources/terms",
      },
      {
        text: "Types",
        link: "/resources/types",
      },
      {
        text: "FAQs",
        link: "/resources/faqs",
      },
      {
        text: "Contact us",
        link: "/resources/contact-us",
      },
    ],
  },
];
