// This file is autogenerated, see scripts/prebuild.ts
import { SidebarItem } from "vocs";

export const aaSdkCoreReferenceSidebar: SidebarItem[] = [
  {
    text: "@aa-sdk/core",
    items: [
      {
        text: "Overview",
        link: "/reference/aa-sdk/core",
      },
    ],
  },
  {
    text: "Functions",
    items: [
      {
        text: "allEqual",
        link: "/reference/aa-sdk/core/functions/allEqual",
      },
      {
        text: "asyncPipe",
        link: "/reference/aa-sdk/core/functions/asyncPipe",
      },
      {
        text: "buildUserOperation",
        link: "/reference/aa-sdk/core/functions/buildUserOperation",
      },
      {
        text: "buildUserOperationFromTx",
        link: "/reference/aa-sdk/core/functions/buildUserOperationFromTx",
      },
      {
        text: "buildUserOperationFromTxs",
        link: "/reference/aa-sdk/core/functions/buildUserOperationFromTxs",
      },
      {
        text: "bundlerActions",
        link: "/reference/aa-sdk/core/functions/bundlerActions",
      },
      {
        text: "checkGasSponsorshipEligibility",
        link: "/reference/aa-sdk/core/functions/checkGasSponsorshipEligibility",
      },
      {
        text: "convertChainIdToCoinType",
        link: "/reference/aa-sdk/core/functions/convertChainIdToCoinType",
      },
      {
        text: "convertCoinTypeToChain",
        link: "/reference/aa-sdk/core/functions/convertCoinTypeToChain",
      },
      {
        text: "convertCoinTypeToChainId",
        link: "/reference/aa-sdk/core/functions/convertCoinTypeToChainId",
      },
      {
        text: "createBundlerClient",
        link: "/reference/aa-sdk/core/functions/createBundlerClient",
      },
      {
        text: "createBundlerClientFromExisting",
        link: "/reference/aa-sdk/core/functions/createBundlerClientFromExisting",
      },
      {
        text: "createSimpleSmartAccount",
        link: "/reference/aa-sdk/core/functions/createSimpleSmartAccount",
      },
      {
        text: "createSmartAccountClient",
        link: "/reference/aa-sdk/core/functions/createSmartAccountClient",
      },
      {
        text: "createSmartAccountClientFromExisting",
        link: "/reference/aa-sdk/core/functions/createSmartAccountClientFromExisting",
      },
      {
        text: "deepHexlify",
        link: "/reference/aa-sdk/core/functions/deepHexlify",
      },
      {
        text: "defaultFeeEstimator",
        link: "/reference/aa-sdk/core/functions/defaultFeeEstimator",
      },
      {
        text: "defaultGasEstimator",
        link: "/reference/aa-sdk/core/functions/defaultGasEstimator",
      },
      {
        text: "defaultPaymasterAndData",
        link: "/reference/aa-sdk/core/functions/defaultPaymasterAndData",
      },
      {
        text: "defaultUserOpSigner",
        link: "/reference/aa-sdk/core/functions/defaultUserOpSigner",
      },
      {
        text: "dropAndReplaceUserOperation",
        link: "/reference/aa-sdk/core/functions/dropAndReplaceUserOperation",
      },
      {
        text: "filterUndefined",
        link: "/reference/aa-sdk/core/functions/filterUndefined",
      },
      {
        text: "getAccountAddress",
        link: "/reference/aa-sdk/core/functions/getAccountAddress",
      },
      {
        text: "getChain",
        link: "/reference/aa-sdk/core/functions/getChain",
      },
      {
        text: "getEntryPoint",
        link: "/reference/aa-sdk/core/functions/getEntryPoint",
      },
      {
        text: "isEntryPointVersion",
        link: "/reference/aa-sdk/core/functions/isEntryPointVersion",
      },
      {
        text: "isSigner",
        link: "/reference/aa-sdk/core/functions/isSigner",
      },
      {
        text: "isSmartAccountClient",
        link: "/reference/aa-sdk/core/functions/isSmartAccountClient",
      },
      {
        text: "isSmartAccountWithSigner",
        link: "/reference/aa-sdk/core/functions/isSmartAccountWithSigner",
      },
      {
        text: "middlewareActions",
        link: "/reference/aa-sdk/core/functions/middlewareActions",
      },
      {
        text: "noopMiddleware",
        link: "/reference/aa-sdk/core/functions/noopMiddleware",
      },
      {
        text: "parseFactoryAddressFromAccountInitCode",
        link: "/reference/aa-sdk/core/functions/parseFactoryAddressFromAccountInitCode",
      },
      {
        text: "pick",
        link: "/reference/aa-sdk/core/functions/pick",
      },
      {
        text: "resolveProperties",
        link: "/reference/aa-sdk/core/functions/resolveProperties",
      },
      {
        text: "sendTransaction",
        link: "/reference/aa-sdk/core/functions/sendTransaction",
      },
      {
        text: "sendTransactions",
        link: "/reference/aa-sdk/core/functions/sendTransactions",
      },
      {
        text: "sendUserOperation",
        link: "/reference/aa-sdk/core/functions/sendUserOperation",
      },
      {
        text: "smartAccountClientActions",
        link: "/reference/aa-sdk/core/functions/smartAccountClientActions",
      },
      {
        text: "split",
        link: "/reference/aa-sdk/core/functions/split",
      },
      {
        text: "toRecord",
        link: "/reference/aa-sdk/core/functions/toRecord",
      },
      {
        text: "toSmartContractAccount",
        link: "/reference/aa-sdk/core/functions/toSmartContractAccount",
      },
      {
        text: "waitForUserOperationTransaction",
        link: "/reference/aa-sdk/core/functions/waitForUserOperationTransaction",
      },
      {
        text: "wrapSignatureWith6492",
        link: "/reference/aa-sdk/core/functions/wrapSignatureWith6492",
      },
    ],
  },
];
