// This file is autogenerated, see scripts/prebuild.ts
import { SidebarItem } from "vocs";

export const aaSdkEthersReferenceSidebar: SidebarItem[] = [
  {
    text: "@aa-sdk/ethers",
    items: [
      {
        text: "Overview",
        link: "/reference/aa-sdk/ethers",
      },
    ],
  },
  {
    text: "Functions",
    items: [],
  },
];
