// This file is autogenerated, see scripts/prebuild.ts
import { SidebarItem } from "vocs";

export const aaSdkEthersReferenceSidebar: SidebarItem[] = [
  {
    text: "@aa-sdk/ethers",
    items: [
      {
        text: "Overview",
        link: "/reference/aa-sdk/ethers",
      },
    ],
  },
  {
    text: "Functions",
    items: [
      {
        text: "convertEthersSignerToAccountSigner",
        link: "/reference/aa-sdk/ethers/functions/convertEthersSignerToAccountSigner",
      },
      {
        text: "convertWalletToAccountSigner",
        link: "/reference/aa-sdk/ethers/functions/convertWalletToAccountSigner",
      },
    ],
  },
  {
    text: "Classes",
    items: [
      {
        text: "AccountSigner",
        items: [
          {
            text: "connect",
            link: "/reference/aa-sdk/ethers/classes/AccountSigner/connect",
          },
          {
            text: "constructor",
            link: "/reference/aa-sdk/ethers/classes/AccountSigner/constructor",
          },
          {
            text: "getAddress",
            link: "/reference/aa-sdk/ethers/classes/AccountSigner/getAddress",
          },
          {
            text: "getBundlerClient",
            link: "/reference/aa-sdk/ethers/classes/AccountSigner/getBundlerClient",
          },
          {
            text: "sendTransaction",
            link: "/reference/aa-sdk/ethers/classes/AccountSigner/sendTransaction",
          },
          {
            text: "signMessage",
            link: "/reference/aa-sdk/ethers/classes/AccountSigner/signMessage",
          },
          {
            text: "signTransaction",
            link: "/reference/aa-sdk/ethers/classes/AccountSigner/signTransaction",
          },
        ],
      },
      {
        text: "EthersProviderAdapter",
        items: [
          {
            text: "connectToAccount",
            link: "/reference/aa-sdk/ethers/classes/EthersProviderAdapter/connectToAccount",
          },
          {
            text: "constructor",
            link: "/reference/aa-sdk/ethers/classes/EthersProviderAdapter/constructor",
          },
          {
            text: "fromEthersProvider",
            link: "/reference/aa-sdk/ethers/classes/EthersProviderAdapter/fromEthersProvider",
          },
          {
            text: "getBundlerClient",
            link: "/reference/aa-sdk/ethers/classes/EthersProviderAdapter/getBundlerClient",
          },
          {
            text: "send",
            link: "/reference/aa-sdk/ethers/classes/EthersProviderAdapter/send",
          },
        ],
      },
    ],
  },
  {
    text: "Resources",
    items: [
      {
        text: "React Native",
        items: [
          {
            text: "Overview",
            link: "/react-native/overview",
          },
          {
            text: "Getting Started",
            items: [
              {
                text: "Getting started on Expo",
                link: "/react-native/getting-started/getting-started-expo",
              },
              {
                text: "Getting started on Bare React Native",
                link: "/react-native/getting-started/getting-started-rn-bare",
              },
            ],
          },
          {
            text: "Using the Signer",
            items: [
              {
                text: "Overview",
                link: "/react-native/signer/overview",
              },
              {
                text: "Setup",
                link: "/react-native/signer/setup-guide",
              },
              {
                text: "Authenticating Users",
                link: "/react-native/signer/authenticating-users",
              },
              {
                text: "Bare React Native Installation",
                link: "/react-native/signer/bare-installation",
              },
            ],
          },
        ],
        collapsed: true,
      },
      {
        text: "Third Party",
        items: [
          {
            text: "Bundlers",
            link: "/third-party/bundlers",
          },
          {
            text: "Chains",
            link: "/third-party/chains",
          },
          {
            text: "Paymasters",
            link: "/third-party/paymasters",
          },
          {
            text: "Signers",
            link: "/third-party/signers",
          },
          {
            text: "Smart Contracts",
            link: "/third-party/smart-contracts",
          },
        ],
        collapsed: true,
      },
      {
        text: "Terms",
        link: "/resources/terms",
      },
      {
        text: "Types",
        link: "/resources/types",
      },
      {
        text: "FAQs",
        link: "/resources/faqs",
      },
      {
        text: "Contact us",
        link: "/resources/contact-us",
      },
    ],
  },
];
