/**
 * Internal registry mapping chain IDs to Alchemy RPC base URLs.
 * This replaces the need for custom chain exports with embedded Alchemy URLs.
 *
 * Auto-generated by the ws-tools CLI — do not manually edit.
 */
export const ALCHEMY_RPC_MAPPING: Record<number, string> = {
  // ABSTRACT networks
  11124: "https://abstract-testnet.g.alchemy.com/v2", // abstractTestnet
  2741: "https://abstract-mainnet.g.alchemy.com/v2", // abstractMainnet

  // ADI networks
  99999: "https://adi-testnet.g.alchemy.com/v2", // adiTestnet
  36900: "https://adi-mainnet.g.alchemy.com/v2", // adiMainnet

  // ANIME networks
  6900: "https://anime-sepolia.g.alchemy.com/v2", // animeSepolia
  69000: "https://anime-mainnet.g.alchemy.com/v2", // animeMainnet

  // APECHAIN networks
  33139: "https://apechain-mainnet.g.alchemy.com/v2", // apechainMainnet
  33111: "https://apechain-curtis.g.alchemy.com/v2", // apechainCurtis

  // ARB networks
  421614: "https://arb-sepolia.g.alchemy.com/v2", // arbSepolia
  42161: "https://arb-mainnet.g.alchemy.com/v2", // arbMainnet

  // ARBNOVA networks
  42170: "https://arbnova-mainnet.g.alchemy.com/v2", // arbnovaMainnet

  // ARC networks
  5042002: "https://arc-testnet.g.alchemy.com/v2", // arcTestnet

  // ASTAR networks
  592: "https://astar-mainnet.g.alchemy.com/v2", // astarMainnet

  // AVAX networks
  43114: "https://avax-mainnet.g.alchemy.com/v2", // avaxMainnet
  43113: "https://avax-fuji.g.alchemy.com/v2", // avaxFuji

  // BASE networks
  8453: "https://base-mainnet.g.alchemy.com/v2", // baseMainnet
  84532: "https://base-sepolia.g.alchemy.com/v2", // baseSepolia

  // BERACHAIN networks
  80094: "https://berachain-mainnet.g.alchemy.com/v2", // berachainMainnet
  80069: "https://berachain-bepolia.g.alchemy.com/v2", // berachainBepolia

  // BLAST networks
  81457: "https://blast-mainnet.g.alchemy.com/v2", // blastMainnet
  168587773: "https://blast-sepolia.g.alchemy.com/v2", // blastSepolia

  // BNB networks
  97: "https://bnb-testnet.g.alchemy.com/v2", // bnbTestnet
  56: "https://bnb-mainnet.g.alchemy.com/v2", // bnbMainnet

  // BOB networks
  60808: "https://bob-mainnet.g.alchemy.com/v2", // bobMainnet
  808813: "https://bob-sepolia.g.alchemy.com/v2", // bobSepolia

  // BOTANIX networks
  3636: "https://botanix-testnet.g.alchemy.com/v2", // botanixTestnet
  3637: "https://botanix-mainnet.g.alchemy.com/v2", // botanixMainnet

  // CELO networks
  11142220: "https://celo-sepolia.g.alchemy.com/v2", // celoSepolia
  42220: "https://celo-mainnet.g.alchemy.com/v2", // celoMainnet

  // CITREA networks
  4114: "https://citrea-mainnet.g.alchemy.com/v2", // citreaMainnet
  5115: "https://citrea-testnet.g.alchemy.com/v2", // citreaTestnet

  // CLANKERMON networks
  510525: "https://clankermon-mainnet.g.alchemy.com/v2", // clankermonMainnet

  // CROSSFI networks
  4157: "https://crossfi-testnet.g.alchemy.com/v2", // crossfiTestnet
  4158: "https://crossfi-mainnet.g.alchemy.com/v2", // crossfiMainnet

  // DEGEN networks
  666666666: "https://degen-mainnet.g.alchemy.com/v2", // degenMainnet

  // ETH networks
  1: "https://eth-mainnet.g.alchemy.com/v2", // ethMainnet
  11155111: "https://eth-sepolia.g.alchemy.com/v2", // ethSepolia

  // FLOW networks
  747: "https://flow-mainnet.g.alchemy.com/v2", // flowMainnet
  545: "https://flow-testnet.g.alchemy.com/v2", // flowTestnet

  // FRAX networks
  252: "https://frax-mainnet.g.alchemy.com/v2", // fraxMainnet

  // GENSYN networks
  685685: "https://gensyn-testnet.g.alchemy.com/v2", // gensynTestnet

  // GNOSIS networks
  100: "https://gnosis-mainnet.g.alchemy.com/v2", // gnosisMainnet
  10200: "https://gnosis-chiado.g.alchemy.com/v2", // gnosisChiado

  // HUMANITY networks
  7080969: "https://humanity-testnet.g.alchemy.com/v2", // humanityTestnet

  // HYPERLIQUID networks
  999: "https://hyperliquid-mainnet.g.alchemy.com/v2", // hyperliquidMainnet

  // INK networks
  57073: "https://ink-mainnet.g.alchemy.com/v2", // inkMainnet
  763373: "https://ink-sepolia.g.alchemy.com/v2", // inkSepolia

  // LENS networks
  37111: "https://lens-sepolia.g.alchemy.com/v2", // lensSepolia

  // LINEA networks
  59144: "https://linea-mainnet.g.alchemy.com/v2", // lineaMainnet
  59141: "https://linea-sepolia.g.alchemy.com/v2", // lineaSepolia

  // MANTLE networks
  5000: "https://mantle-mainnet.g.alchemy.com/v2", // mantleMainnet
  5003: "https://mantle-sepolia.g.alchemy.com/v2", // mantleSepolia

  // MATIC networks
  80002: "https://polygon-amoy.g.alchemy.com/v2", // maticAmoy
  137: "https://polygon-mainnet.g.alchemy.com/v2", // maticMainnet

  // MEGAETH networks
  4326: "https://megaeth-mainnet.g.alchemy.com/v2", // megaethMainnet
  6343: "https://megaeth-testnet.g.alchemy.com/v2", // megaethTestnet

  // METIS networks
  1088: "https://metis-mainnet.g.alchemy.com/v2", // metisMainnet

  // MODE networks
  919: "https://mode-sepolia.g.alchemy.com/v2", // modeSepolia
  34443: "https://mode-mainnet.g.alchemy.com/v2", // modeMainnet

  // MONAD networks
  10143: "https://monad-testnet.g.alchemy.com/v2", // monadTestnet
  143: "https://monad-mainnet.g.alchemy.com/v2", // monadMainnet

  // MOONBEAM networks
  1284: "https://moonbeam-mainnet.g.alchemy.com/v2", // moonbeamMainnet

  // MYTHOS networks
  42018: "https://mythos-mainnet.g.alchemy.com/v2", // mythosMainnet

  // OPBNB networks
  5611: "https://opbnb-testnet.g.alchemy.com/v2", // opbnbTestnet
  204: "https://opbnb-mainnet.g.alchemy.com/v2", // opbnbMainnet

  // OPENLOOT networks
  905905: "https://openloot-sepolia.g.alchemy.com/v2", // openlootSepolia

  // OPT networks
  10: "https://opt-mainnet.g.alchemy.com/v2", // optMainnet
  11155420: "https://opt-sepolia.g.alchemy.com/v2", // optSepolia

  // PLASMA networks
  9746: "https://plasma-testnet.g.alchemy.com/v2", // plasmaTestnet
  9745: "https://plasma-mainnet.g.alchemy.com/v2", // plasmaMainnet

  // POLYGONZKEVM networks
  2442: "https://polygonzkevm-cardona.g.alchemy.com/v2", // polygonzkevmCardona
  1101: "https://polygonzkevm-mainnet.g.alchemy.com/v2", // polygonzkevmMainnet

  // POLYNOMIAL networks
  8008: "https://polynomial-mainnet.g.alchemy.com/v2", // polynomialMainnet
  80008: "https://polynomial-sepolia.g.alchemy.com/v2", // polynomialSepolia

  // RISE networks
  11155931: "https://rise-testnet.g.alchemy.com/v2", // riseTestnet

  // ROBINHOOD networks
  46630: "https://robinhood-testnet.g.alchemy.com/v2", // robinhoodTestnet

  // RONIN networks
  2020: "https://ronin-mainnet.g.alchemy.com/v2", // roninMainnet
  202601: "https://ronin-saigon.g.alchemy.com/v2", // roninSaigon

  // ROOTSTOCK networks
  30: "https://rootstock-mainnet.g.alchemy.com/v2", // rootstockMainnet
  31: "https://rootstock-testnet.g.alchemy.com/v2", // rootstockTestnet

  // SCROLL networks
  534352: "https://scroll-mainnet.g.alchemy.com/v2", // scrollMainnet
  534351: "https://scroll-sepolia.g.alchemy.com/v2", // scrollSepolia

  // SEI networks
  1329: "https://sei-mainnet.g.alchemy.com/v2", // seiMainnet
  1328: "https://sei-testnet.g.alchemy.com/v2", // seiTestnet

  // SETTLUS networks
  5371: "https://settlus-mainnet.g.alchemy.com/v2", // settlusMainnet
  5373: "https://settlus-septestnet.g.alchemy.com/v2", // settlusSeptestnet

  // SHAPE networks
  11011: "https://shape-sepolia.g.alchemy.com/v2", // shapeSepolia
  360: "https://shape-mainnet.g.alchemy.com/v2", // shapeMainnet

  // SONEIUM networks
  1946: "https://soneium-minato.g.alchemy.com/v2", // soneiumMinato
  1868: "https://soneium-mainnet.g.alchemy.com/v2", // soneiumMainnet

  // SONIC networks
  57054: "https://sonic-blaze.g.alchemy.com/v2", // sonicBlaze
  14601: "https://sonic-testnet.g.alchemy.com/v2", // sonicTestnet
  146: "https://sonic-mainnet.g.alchemy.com/v2", // sonicMainnet

  // STABLE networks
  988: "https://stable-mainnet.g.alchemy.com/v2", // stableMainnet
  2201: "https://stable-testnet.g.alchemy.com/v2", // stableTestnet

  // STORY networks
  1514: "https://story-mainnet.g.alchemy.com/v2", // storyMainnet
  1315: "https://story-aeneid.g.alchemy.com/v2", // storyAeneid

  // TEA networks
  10218: "https://tea-sepolia.g.alchemy.com/v2", // teaSepolia

  // TEMPO networks
  42431: "https://tempo-moderato.g.alchemy.com/v2", // tempoModerato
  42429: "https://tempo-testnet.g.alchemy.com/v2", // tempoTestnet

  // TRON networks
  728126428: "https://tron-mainnet.g.alchemy.com/v2", // tronMainnet
  3448148188: "https://tron-testnet.g.alchemy.com/v2", // tronTestnet

  // UNICHAIN networks
  1301: "https://unichain-sepolia.g.alchemy.com/v2", // unichainSepolia
  130: "https://unichain-mainnet.g.alchemy.com/v2", // unichainMainnet

  // UNITE networks
  88899: "https://unite-mainnet.g.alchemy.com/v2", // uniteMainnet
  888991: "https://unite-testnet.g.alchemy.com/v2", // uniteTestnet

  // WORLDCHAIN networks
  4801: "https://worldchain-sepolia.g.alchemy.com/v2", // worldchainSepolia
  480: "https://worldchain-mainnet.g.alchemy.com/v2", // worldchainMainnet

  // WORLDMOBILECHAIN networks
  869: "https://worldmobilechain-mainnet.g.alchemy.com/v2", // worldmobilechainMainnet

  // ZETACHAIN networks
  7001: "https://zetachain-testnet.g.alchemy.com/v2", // zetachainTestnet
  7000: "https://zetachain-mainnet.g.alchemy.com/v2", // zetachainMainnet

  // ZKSYNC networks
  324: "https://zksync-mainnet.g.alchemy.com/v2", // zksyncMainnet
  300: "https://zksync-sepolia.g.alchemy.com/v2", // zksyncSepolia

  // ZORA networks
  7777777: "https://zora-mainnet.g.alchemy.com/v2", // zoraMainnet
  999999999: "https://zora-sepolia.g.alchemy.com/v2", // zoraSepolia
};

/**
 * Gets the Alchemy RPC base URL for a given chain ID.
 *
 * @param {number} chainId The chain ID to lookup
 * @returns {string | undefined} The Alchemy RPC base URL or undefined if not supported
 *
 * @example
 * ```ts
 * const rpcUrl = getAlchemyRpcUrl(1); // "https://eth-mainnet.g.alchemy.com/v2"
 * ```
 */
export function getAlchemyRpcUrl(chainId: number): string | undefined {
  return ALCHEMY_RPC_MAPPING[chainId];
}

/**
 * Checks if a chain ID is supported by the Alchemy RPC registry.
 *
 * @param {number} chainId The chain ID to check
 * @returns {boolean} True if the chain is supported, false otherwise
 */
export function isChainSupported(chainId: number): boolean {
  return chainId in ALCHEMY_RPC_MAPPING;
}

/**
 * Gets all supported chain IDs from the registry.
 *
 * @returns {number[]} Array of supported chain IDs
 */
export function getSupportedChainIds(): number[] {
  return Object.keys(ALCHEMY_RPC_MAPPING).map(Number);
}
