export const API_KEY = process.env.API_KEY!;
export const PAYMASTER_POLICY_ID = process.env.PAYMASTER_POLICY_ID!;
export const LIGHT_ACCOUNT_OWNER_MNEMONIC =
  process.env.LIGHT_ACCOUNT_OWNER_MNEMONIC!;
export const MODULAR_MULTISIG_ACCOUNT_OWNER_MNEMONIC =
  process.env.MODULAR_MULTISIG_ACCOUNT_OWNER_MNEMONIC!;
export const MODULAR_MULTIOWNER_ACCOUNT_OWNER_MNEMONIC =
  process.env.MODULAR_MULTIOWNER_ACCOUNT_OWNER_MNEMONIC!;
