import dedent from "dedent";
import ts from "typescript";

export function functionTemplate(
  functionName: string,
  packageName: string,
  jsDocCommentAndTags: readonly (ts.JSDoc | ts.JSDocTag)[]
) {
  const comment = jsDocCommentAndTags.find(
    (x) => x.kind === ts.SyntaxKind.JSDoc
  ) as ts.JSDoc;
  const exampleTag = comment.tags?.find(
    (x) =>
      x.kind === ts.SyntaxKind.JSDocTag && x.tagName.escapedText === "example"
  );

  const parameterTags = comment.tags?.filter(
    (x) => x.kind === ts.SyntaxKind.JSDocParameterTag
  ) as ts.JSDocParameterTag[];
  const parameters = parameterTags.map((tag) => {
    const type = tag.typeExpression?.type;
    return {
      name: tag.name.getText(),
      type: type?.getText(),
      description: tag.comment,
    };
  });

  const parameterSection = parameters.length
    ? dedent`

    ## Parameters
    ${parameters
      .map(
        (param) => dedent`
    ### ${param.name}
    \`${param.type}\`
    ${param.description}
    `
      )
      .join("\n\n")}
    \n
    `
    : "";

  const returnTag = comment.tags?.find(
    (x) => x.kind === ts.SyntaxKind.JSDocReturnTag
  ) as ts.JSDocReturnTag | undefined;

  const returnSection = returnTag
    ? dedent`
    ## Returns
    \`${returnTag.typeExpression?.type?.getFullText()?.trim()}\`
    ${(returnTag && ts.getTextOfJSDocComment(returnTag?.comment)) ?? ""}
    `
    : "";

  const exampleSection = exampleTag
    ? dedent`
    ## Usage
    ${ts.getTextOfJSDocComment(exampleTag.comment)?.trim()}
    `
    : "";

  return dedent`
    ---
    # This file is autogenerated
    title: ${functionName}
    description: Overview of the ${functionName} method
    ---

    # ${functionName}
    ${ts.getTextOfJSDocComment(comment?.comment)}

    ## Import
    \`\`\`ts
    import { ${functionName} } from "${packageName}";
    \`\`\`
    ${exampleSection}
    ${parameterSection}
    ${returnSection}
  `;
}
