const reactHookGroupings = {
  Authentication: [
    "useAddOauthProvider",
    "useAuthContext",
    "useAuthModal",
    "useAddPasskey",
    "useAuthenticate",
    "useConnect",
    "useExportAccount",
    "useMFA",
    "useListAuthMethods",
    "useLogout",
    "useRemoveEmail",
    "useRemoveOauthProvider",
    "useRemovePasskey",
    "useSetEmail",
    "useSigner",
    "useSignerStatus",
    "useUser",
  ],
  "Account Client": ["useAccount", "useSmartAccountClient"],
  "Smart Account Actions": [
    "useSendUserOperation",
    "useSignMessage",
    "useSignTypedData",
    "useWaitForUserOperationTransaction",
    "useDropAndReplaceUserOperation",
    "useClientActions",
    "useChain",
  ],
  "Bundler/RPC Client": ["useBundlerClient"],
  Utilities: [
    "useAlchemyAccountContext",
    "useUiConfig",
    "useConnection",
    "useAuthError",
  ],
};

export default reactHookGroupings;
