name: Documentation Lint

on:
  pull_request:
    paths:
      - 'docs/**/*.mdx'
      - '.vale.ini'
      - '.vale/**'

jobs:
  vale:
    runs-on: ubuntu-latest
    name: Vale Documentation Linting
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Vale
        uses: jaxxstorm/action-install-gh-release@v1.12.0
        with:
          repo: errata-ai/vale
          tag: v3.12.0
          cache: enable

      - name: Run Vale
        run: vale docs/**/*.mdx
