name: Documentation Lint

on:
  pull_request:
    paths:
      - 'docs/**/*.mdx'
      - '.vale.ini'
      - '.vale/**'

jobs:
  vale:
    runs-on: ubuntu-latest
    name: Vale Documentation Linting
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Vale Linting
        uses: errata-ai/vale-action@reviewdog
        with:
          # Run Vale on all documentation files
          files: docs
          # Use Vale version that supports our configuration
          version: 3.12.0
          # Only report errors, not suggestions
          level: error
        env:
          # Required for posting PR comments
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
