name: Publish Docs

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && contains(github.ref, 'refs/heads/main') && github.run_number > 1 }}
    steps:
      - name: Setup Docs
        uses: ./.github/actions/setup-docs
        with:
          docs-github-token: ${{ secrets.DOCS_GITHUB_TOKEN }}

      - name: Publish Docs
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: |
          cd docs-site
          fern generate --docs --log-level debug
