name: Publish Docs

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    if: ${{ github.event_name == 'push' && contains(github.ref, 'refs/heads/main') && github.run_number > 1 }}
    steps:
      - name: Checkout aa-sdk
        uses: actions/checkout@v4
      - name: Setup Docs
        uses: ./.github/actions/setup-docs
        with:
          docs-github-token: ${{ secrets.DOCS_GITHUB_TOKEN }}

      - name: Generate Fern Docs
        id: publish
        uses: ./.github/actions/publish-fern
        with:
          github-token: ${{ github.token }}
          fern-token: ${{ secrets.FERN_TOKEN }}
          environment: docs-production
          ref: ${{ github.ref }}
