name: Publish Docs

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    if: ${{ github.event_name == 'push' && contains(github.ref, 'refs/heads/main') && github.run_number > 1 }}
    steps:
      - name: Checkout aa-sdk
        uses: actions/checkout@v5
      - name: Setup Docs
        uses: ./.github/actions/setup-docs

      - name: Generate Fern Docs
        id: publish
        uses: ./.github/actions/publish-fern
        with:
          github-token: ${{ github.token }}
          fern-token: ${{ secrets.FERN_TOKEN }}
          environment: docs-production
          ref: ${{ github.ref }}

      - name: Trigger GitHub Pages Deploy Workflow
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.DOCS_GH_PAGES_DEPLOY_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/alchemyplatform/docs/dispatches \
            -d '{"event_type":"trigger-gh-pages-deploy","client_payload":{"source":"alchemyplatform/aa-sdk"}}'
